module.exports = function(app) {
    var APIroute = require('../controllers/Controllers');
    // API Routes
    app.route('/')
    .all(APIroute.home)
    app.route('/users/register')
    .post(APIroute.register)
    app.route('/users/login')
    .post(APIroute.login)
    app.route('/users/')
    .get(APIroute.get_profile)
    app.route('/trello/board')
    .post(APIroute.create_board)
    .get(APIroute.get_board_by_uuid)
    app.route('/trello/list')
    .post(APIroute.create_list)
    .put(APIroute.update_list)
    .delete(APIroute.delete_list)
    app.route("/trello/card")
    .post(APIroute.create_card)
    .delete(APIroute.delete_card)
    .put(APIroute.update_card)
    app.route('/users/board')
    .get(APIroute.get_board_from_user)
    app.route('/trello/drag')
    .post(APIroute.drag_and_drop)
    app.route('/users/board/add_permission')
    .post(APIroute.add_permission)
  };
